### ISSUE TITLE
ゲームが終わると音楽は終わるが、ドロイドが同じタイミングで消えない

### ISSUE THREAD

**Issue by Rikyu3** [Rikyu3/moguratataki#4]

**Comment by Rikyu3** [comment]
//ドロイド君の最大数を減らす
					maxDroid--;
					console.log(maxDroid);
					//もしこれ以上ドロイド君は出現しないなら、穴を塞ぐ
					if(maxDroid<=0) {
						this.mode=3;
					}
				}
				break;
			case 2://待つ
				if(game.frame>this.waitFor){
					this.mode = this.nextMode;
				}
				break;
			case 3://なにもしない(この穴からもうドロイド君は出ない)
				// console.log("test");
				sound2.stop();
				break;
		}
	},

ここでドロイドの数を減らしていっているから、
ここら辺を変えたらいいのかなと思っています。

**Comment by tatsukawa** [comment]
順に説明していくと，
1. https://github.com/Rikyu3/moguratataki/blob/master/main.js#L104-L109

    ここで，Pitクラスのインスタンスを16個生成して，game.rootSceneに追加しています．

2. それぞれのインスタンスは，独立して https://github.com/Rikyu3/moguratataki/blob/master/main.js#L20-L57 を実行しています．
3. ところが，変数`sound2`は，https://github.com/Rikyu3/moguratataki/blob/master/main.js#L5 で宣言されているように，グローバル変数になります．
なので，https://github.com/Rikyu3/moguratataki/blob/master/main.js#L54 で`sound2`を`stop`させちゃうと，16個のPitクラスのインスタンスの内，一番最初にmode=3になった時点で音楽を止めてしまうことを意味しています．

と，いうことで音楽が止まった後に，残りの15個のドロイドオブジェクトが出現してから，ゲームが終了するといった挙動をします．
